Have run-parallel.sh catch psub errors, and report them clearly.

diff --git a/src/scripts/psub b/src/scripts/psub
--- a/src/scripts/psub
+++ b/src/scripts/psub
@@ -75,6 +75,7 @@ Further notes:
 }
 
 error_exit() {
+   echo -n "psub fatal error: " >&2
    for msg in "$@"; do
       echo $msg >&2
    done
